@HostAddress = http://localhost:5112
@Id = paste_the_id_here

### Create a Valid Product (Expected: 200 OK)
POST {{HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Mechanical Keyboard",
    "description": "High-quality mechanical keyboard with tactile switches.",
    "price": 129.99,
    "stockQuantity": 50
}

### Create an Invalid Product (Expected: 400 Bad Request with ProblemDetails)
POST {{HostAddress}}/api/products
Content-Type: application/json

{
    "name": "product",
    "price": 0,
    "stockQuantity": 0
}

### Get All Products
GET {{HostAddress}}/api/products

### Get Product By Id
GET {{HostAddress}}/api/products/{{Id}}

### Update a Product
PUT {{HostAddress}}/api/products/{{Id}}
Content-Type: application/json

{
    "id": "{{Id}}",
    "name": "Mechanical Keyboard v2",
    "description": "Updated version with optical switches.",
    "price": 149.99,
    "stockQuantity": 40
}

### Add Stock to Product
PATCH {{HostAddress}}/api/products/{{Id}}/add-stock
Content-Type: application/json

{
    "id": "{{Id}}",
    "quantity": 10
}

### Deduct Stock from Product
PATCH {{HostAddress}}/api/products/{{Id}}/deduct-stock
Content-Type: application/json

{
    "id": "{{Id}}",
    "quantity": 5
}