@HostAddress = http://localhost:5112

### Create a Valid Product (Expected: 200 OK)
POST {{HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Mechanical Keyboard",
    "description": "High-quality mechanical keyboard with tactile switches.",
    "price": 129.99,
    "stockQuantity": 50
}

### Create an Invalid Product (Expected: 400 Bad Request with ProblemDetails)
POST {{HostAddress}}/api/products
Content-Type: application/json

{
    "name": "",
    "price": -34.99,
    "stockQuantity": -100
}

### Get All Products
GET {{HostAddress}}/api/products

### Get Product By Id
GET {{HostAddress}}/api/products/727fff51-480c-4894-bf0b-722949a085ee