@HostAddress = http://localhost:5112

### Create a Valid Product (Expected: 200 OK)
POST {{HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Mechanical Keyboard",
    "description": "High-quality mechanical keyboard with tactile switches.",
    "price": 129.99,
    "stockQuantity": 50
}

### Create an Invalid Product (Expected: 400 Bad Request with ProblemDetails)
POST {{HostAddress}}/api/products
Content-Type: application/json

{
    "name": "product",
    "price": 0,
    "stockQuantity": 0
}

### Get All Products
GET {{HostAddress}}/api/products

### Get Product By Id
GET {{HostAddress}}/api/products/727fff51-480c-4894-bf0b-722949a085ee

### Update a Product
PUT {{HostAddress}}/api/products/727fff51-480c-4894-bf0b-722949a085ef
Content-Type: application/json

{
    "id": "727fff51-480c-4894-bf0b-722949a085ef",
    "name": "Mechanical Keyboard v2",
    "description": "Updated version with optical switches.",
    "price": 149.99,
    "stockQuantity": 40
}